name: Increment Version on Merge
on:
  pull_request:
    types: [closed]

jobs:
  increment-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/Crediayni/git-version-lite for more details around how to increment major/minor/patch through commit messages
      - name: Increment the version
        uses: Crediayni/git-version-lite@main
        with:
          default-release-type: major
